### ISSUE TITLE
Tabs are still filtered by window when changing to the new mode

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#105]
The tab manager only shows the last window (1st when I tried) no matter which one you select.

This is a bug when changing between the classic mode and the new mode. While being in the classic mode with a window selected and then changing to the new mode, the tabs are still filtered by the window. Then, when you try to go to another window, there will be an error with the jQuery selector because the window doesn't exist (there is only one window when all of them should be there in the new mode)

![image](https://user-images.githubusercontent.com/25534385/40951236-11e28258-68b1-11e8-9c01-3dd260f5e1fe.png)

**Comment by adamjamesadair** [comment]
#107 resolves this issue.
