### ISSUE TITLE
Give feedback when a window is selected

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#118]
Highlight the corresponding window when window buttons are clicked.

Partially solved in https://github.com/adamjamesadair/manage-my-tabs/pull/117. It just changes the background color for a period of time. More style properties could be added, like changing the contour, zoom in and out and some other cool FX

**Comment by adamjamesadair** [comment]
Adding more effects like zoom draw too much attention to the animation and feel excessive. Keeping the animation to a simple color change as in #117 is enough.
