### ISSUE TITLE
Undo closing windows doesn't work on Firefox

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#127]
It happened in this commit https://github.com/adamjamesadair/manage-my-tabs/commit/7c2a7fce0c80d5d8070126662834115a83ec2625, just for reference for the following error 

> Error: Type error for parameter createData (Property "focused" is unsupported by Firefox) for windows.create. tabManager.js:250:5

To replicate it, close a window with the tab manager and click the "Undo" button

**Comment by adamjamesadair** [comment]
#135 fixes this issue.
