### ISSUE TITLE
Issue of missing tabs after search

### ISSUE THREAD

**Issue by rayman89** [adamjamesadair/manage-my-tabs#129]
When you search for  something and then delete letters groups with multiple tabs that had tabs that appeared in the results of the search only show those tabs and not the rest.

Examples
![image](https://user-images.githubusercontent.com/5449042/41116696-a7f08966-6a50-11e8-8575-d6507e9d33ba.png)

![image](https://user-images.githubusercontent.com/5449042/41116866-1ed04918-6a51-11e8-9e7f-db7fd3a51e28.png)

**Comment by adamjamesadair** [comment]
#134 Fixes this issue.
