### ISSUE TITLE
Search box cursor

### ISSUE THREAD

**Issue by swampferret** [adamjamesadair/manage-my-tabs#170]
Is it possible to have a cursor default into the search box so a search can be done immediately upon activating the Manage My Tabs window without the need to place the cursor in the search box manually?

**Comment by BorFour** [comment]
Yeah, that is a great idea! That is something that I actually miss every time I open the extension. 

It shouldn't be that hard. Just a Javascript statement that sets the cursor into the search box right after the extension is initialized/loaded.

**Comment by adamjamesadair** [comment]
This enhancement has been implemented in the develop branch and will be included in the next release.
