### ISSUE TITLE
Script with util functions

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#44]
https://github.com/adamjamesadair/manage-my-tabs/blob/917f4271d3d2de31ec8130324936a5ad4960ee60/scripts/src/tabManager.js#L207-L215

Maybe this function could be useful for other scripts in the future. What about creating a `utils.js` with all this kind of functions?

**Comment by adamjamesadair** [comment]
@BorFour That sounds like a good idea. Thank you for the suggestion.
