### ISSUE TITLE
Tab limit for tab groups

### ISSUE THREAD

**Issue by adamjamesadair** [adamjamesadair/manage-my-tabs#47]
When a tab groups reaches a certain limit, a new group of that domain is created.
- [x] Main functionality #46 
- [x] Add settings to the settings sidebar #49

**Comment by BorFour** [comment]
This could be updated with the slider for the max number of tabs in the tab group in https://github.com/adamjamesadair/manage-my-tabs/pull/51

**Comment by adamjamesadair** [comment]
@BorFour The issue has been updated. Thank you.
