### ISSUE TITLE
Generic settings and setting manager

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#52]
Right now, it is pretty messy to add new settings. A lot of these have a common structure, such as the HTML element, getting the value from the `chrome.storage`, updating the tabManager when the HTML element changes, etc.

The idea is to make a generic setting class for each type of setting (boolean, range, combobox, etc.) that will manager all these common interactions.

A setting would be defined with the following attributes:

- A unique id (for the HTML object)
- A brief name
- A tooltip describing the setting
- The type of the setting (checkbox, slider, etc.)
- ... ?

**Comment by adamjamesadair** [comment]
Generic settings for checkboxes and radio buttons and general setting improvements were made in #91. Since there are many custom settings being used, this is sufficient for now.
