### ISSUE TITLE
Change "None" option in sort groups settings to "Window order".

### ISSUE THREAD

**Issue by adamjamesadair** [adamjamesadair/manage-my-tabs#54]
The "None" option in sort groups settings is unclear and should be changed to be more clear. When selected, the tab manager displays the tab groups in the order that they appear in the window.

**Comment by BorFour** [comment]
We could put something like _Window order_ or _Displayed order_

**Comment by adamjamesadair** [comment]
@BorFour Thank you for the suggestions! I like the sound of _Window order_.

**Comment by adamjamesadair** [comment]
#75 Adds this feature.
