### ISSUE TITLE
Character encoding of the HTML - firefox

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#64]
Running the extension on Firefox will give the following error

> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

Probably, Google Chrome is able to set a default encoding while Firefox doesn't do it

**Comment by adamjamesadair** [comment]
#70 Resolves this issue.
