### ISSUE TITLE
Click on tab - firefox

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#65]
Clicking on tabs on Firefox gives the following error:

> Error: Type error for parameter updateProperties (Property "highlighted" is unsupported by Firefox) for tabs.update.

Nonetheless, in the following API documentation, `highlighted` seems to be a valid property:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/update

**Comment by adamjamesadair** [comment]
#70 Resolves this issue.
