### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by BorFour** [adamjamesadair/manage-my-tabs#69]
Add shortcuts for some of the functions of the tab manager:

- [x] Open the tab manager extension
- [x] Undo
- [x] Toggle the settings bar #100 
- [x] Arrange tabs #100 
- [x] Navigate to a window
- [x] Toggle 'all windows' mode

**Comment by adamjamesadair** [comment]
@BorFour There is currently a shortcut for Undo, Ctrl + Z for windows and linux or Command + Z for Mac. A section listing the shortcuts should be added with these new shortcuts.

**Comment by adamjamesadair** [comment]
#125 adds some functionality, but to add more than 4 hotkeys, a different implementation will be needed. This can be done in the next release.

**Comment by adamjamesadair** [comment]
#137 Adds the remaining shortcuts.
